### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by philoserf**

### CODE REVIEW

**Comment by skatkov** [comment]
golangci-lint is failing now with a following error:
Error: SA1019: p.Start is deprecated: please use [Program.Run] instead.  (staticcheck)

I would appreciate it if you can fix it, before we merge this PR.

**Comment by philoserf** [comment]
> I would appreciate it if you can fix it, before we merge this PR.

I will take a look this evening. I thought it was some transient test condition but a replay didn’t give us joy either.

**Comment by skatkov** [comment]
If I'm not mistaken, this issue comes because we updated bubbletea framework. We can pin to older version or we have to slightly rewrite how TUI is initiated (method used now was deprecated).

**Comment by philoserf** [comment]
> If I'm not mistaken, this issue comes because we updated bubbletea framework.

Ah. I hadn’t noticed because of the split direct requires. On it in a bit.

**Comment by philoserf** [comment]
I am going to dump this for a new approach.

**Pull request closed without merging**
